version: '3'
services:
  reservation:
    build: .
    ports: 
        - "6000:6000" 
    depends_on:
        - db
  
  db:
    image: mongo
    volumes:
        
        - ./data:/data/
    ports:
        - "27017:27017"
