version: '3'
services:
  web:
    build: .
    ports: 
        - "8080:5000" 
    depends_on:
        - db
  
  db:
    image: mongo
    volumes:
        
        - ./data:/data/
    ports:
        - "27017:27017"

   
