version: '3'
services:
  reservation:
    build: .
    restart: always
    ports: 
        - "6000:5000" 
    depends_on:
        - db
  
  db:
    image: mongo
    volumes: 
        - ./data:/data/
    ports:
        - "27017:27017"
