version: '3'
services:
  webdb:
    build: .
    ports: 
        - "6060:6000" 
    depends_on:
        - db
  
  db:
    image: mongo
    volumes:
        
        - ./data:/data/
    ports:
        - "27017:27017"

  querysensor:
    build: .
    depends_on:
        - db   
  reschecker:
    build: .
    depends_on:
        - db
